# async

ES2017 引用了`async`函数.

## 1.基本用法

`async`函数返回一个`Promise`对象, 可以使用`then`方法添加回调函数.

```js
function timeout(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function asyncPrint(value, ms) {
  await timeout(ms);
  console.log(value);
}

asyncPrint("hello world", 1000);
// 1000ms后打印 "hello world"
```

async 函数多种使用形式:

```js
// 函数声明
async function foo() {}

// 函数表达式
const foo = async function () {};

// 对象的方法
let obj = { async foo() {} };
obj.foo().then(...)

// Class 的方法
class Storage {
  constructor() {
    this.cachePromise = caches.open('avatars');
  }

  async getAvatar(name) {
    const cache = await this.cachePromise;
    return cache.match(`/avatars/${name}.jpg`);
  }
}

const storage = new Storage();
storage.getAvatar('jake').then(…);

// 箭头函数
const foo = async () => {};
```

## 2.语法

`async`函数的语法规则总体上比较简单, 难点是错误处理机制

### 返回 Promise 对象

`async`函数返回一个 Promise 对象, `async`内部的`return`语句返回的值会成为`then`方法回调函数的参数; 内部抛出的错误会使返回的 Promise 对象变为`reject`状态, 抛出的错误对象会被`catch`方法回调函数接受.

```js
async function f() {
  return "hello world";
}

f().then((v) => console.log(v));
// "hello world"
```

```js
async function f() {
  throw new Error("出错了");
}

f().then(
  (v) => console.log("resolve", v),
  (e) => console.log("reject", e)
);
//reject Error: 出错了
```

### Promise对象的状态变化

`async`函数返回的Promise对象, 等到内部所有`await`命令后面的Promise对象执行完, 才会发生状态改变. 除非遇到`return`或者抛出错误.

### await命令

`await`后面的
